/**
 * Filipino speech-recognition context collected from the public navigation and
 * introductory terminology on https://www.jw.org/tl/ (accessed 2026-08-07).
 *
 * This is deliberately a compact terminology list, not a copy of JW.org
 * articles or publications. Multi-word entries give supported browsers better
 * context than isolated tokens when contextual speech biasing is available.
 */
export const FILIPINO_JW_SPEECH_VOCABULARY = [
  'JW.org',
  'Mga Saksi ni Jehova',
  'Saksi ni Jehova',
  'Jehova',
  'Diyos',
  'Maylalang',
  'Bibliya',
  'Jesu-Kristo',
  'Kristiyano',
  'Kaharian ng Diyos',
  'Turo ng Bibliya',
  'Sagot sa mga Tanong sa Bibliya',
  'Paliwanag sa mga Teksto sa Bibliya',
  'Pag-aaral sa Bibliya',
  'Pantulong sa Pag-aaral ng Bibliya',
  'Kapayapaan at Kaligayahan',
  'Pag-aasawa at Pamilya',
  'Pananampalataya sa Diyos',
  'Ang Siyensiya at ang Bibliya',
  'Ang Kasaysayan at ang Bibliya',
  'Bagong Sanlibutang Salin',
  'Mga Bibliya',
  'Aklat',
  'Brosyur',
  'Buklet',
  'Tract',
  'Imbitasyon',
  'Mga Serye ng Artikulo',
  'Magasin',
  'Workbook Para sa Pulong',
  'Ministeryo sa Kaharian',
  'JW Broadcasting',
  'Video',
  'Musika',
  'Audio Drama',
  'Pagbabasa ng Bibliya',
  'Online Library',
  'Karaniwang mga Tanong',
  'Makipag-ugnayan sa Amin',
  'Bethel',
  'Pulong',
  'Memoryal',
  'Kombensiyon',
  'Aktibidad',
  'Mga Karanasan',
  'Buong Daigdig',
  'Donasyon',
  'tagapagturo',
  'paniniwala',
  'organisasyon',
  'panalangin',
  'ministeryo',
  'kongregasyon',
  'mabuting balita',
  'banal na espiritu',
  // Additional words and section names from the jw.org/tl homepage and its
  // navigation (featured topics, library and media links).
  'Pumili ng Paksang Gusto Mo',
  'Basahin ang Bibliya Online',
  'Ang Mabuting Balita Ayon kay Jesus',
  'Ebanghelyo',
  'Panoorin ang Video',
  'Panoorin',
  'Higit Pang Impormasyon',
  'Tingnan ang Iba Pa',
  'Tampok',
  'Matagumpay na Pamilya',
  'Pagkakaibigan',
  'Mahalin ang Iyong Kapuwa',
  'Dumalo sa Pulong',
  'Mag-request ng Pupunta sa Iyo',
  'Mga Kabataan',
  'Mga Bata',
  'Video at Activity Para sa mga Bata',
  'Pambata',
  'pinagmulan ng buhay',
  'Walang-Hanggang Kaligayahan',
  'Maghanap',
  'alamin',
  'matuto',
  'tulong',
  'tanong',
  'sagot',
  'pamilya',
  'kaibigan',
  'pag-asa',
  'kapayapaan',
  'kaligayahan',
  'pananampalataya',
  'pag-ibig',
  'turo',
  'balita',
  'kaharian',
  'buhay',
  'kapuwa',
] as const;

/** Canonical spelling for proper names most often distorted by speech recognition. */
export const FILIPINO_JW_CANONICAL_TERMS: ReadonlyArray<{
  canonical: string;
  aliases: readonly string[];
}> = [
  {canonical: 'JW.org', aliases: ['jw.org', 'jw dot org', 'jay double u dot org']},
  {canonical: 'Mga Saksi ni Jehova', aliases: ['mga saksi ni jehova', 'mga saksi ni jehovah']},
  {canonical: 'Jehova', aliases: ['jehova', 'jehovah']},
  {canonical: 'Jesu-Kristo', aliases: ['jesu-kristo', 'jesu kristo', 'hesu-kristo', 'hesus kristo']},
  {canonical: 'Bagong Sanlibutang Salin', aliases: ['bagong sanlibutang salin']},
  {canonical: 'JW Broadcasting', aliases: ['jw broadcasting', 'jay double u broadcasting']},
  {canonical: 'Bethel', aliases: ['bethel']},
  {canonical: 'Bibliya', aliases: ['bibliya']},
  {
    canonical: 'Ang Mabuting Balita Ayon kay Jesus',
    aliases: ['ang mabuting balita ayon kay jesus', 'ang mabuting balita ayon kay hesus'],
  },
  {canonical: 'Ebanghelyo', aliases: ['ebanghelyo', 'ebanghelio']},
  {canonical: 'Walang-Hanggang Kaligayahan', aliases: ['walang-hanggang kaligayahan', 'walang hanggang kaligayahan']},
  {canonical: 'Mahalin ang Iyong Kapuwa', aliases: ['mahalin ang iyong kapuwa', 'mahalin ang iyong kapwa']},
];
